/*
# version.ts
Stores git version information to src/environments/version-info.ts

Use from components: import { VERSION_INFO } from 'environments/version';

## Dependencies
npm install chalk git-describe path fs-extra --save-dev

## Project Integration
Add src/environments/version.ts to .gitignore
Add this script to your build system, e.g. for npm
     "build": "npm run prestart && ng build",
     "prestart": "node version.ts",
*/

const chalk = require('chalk');
const git = require('git-describe');
const path = require('path');
const fs = require('fs-extra');

const appVersion = require(path.resolve('.', 'package.json')).version;
console.log(chalk.green(`App version is ${appVersion}`));

const info = git.gitDescribeSync(__dirname);
info['app'] = appVersion;
const version_string = chalk.yellow(info.raw);
const json = JSON.stringify(info, null, 4);

const file = path.resolve('.', 'src', 'environments', 'version-info.ts');
const path_string = chalk.yellow(file);

console.log(chalk.green(`Writing version info ${version_string} to ${path_string}`));

fs.outputFileSync(file,
  `// Autogenerated Version Information
/* tslint:disable */
export const VERSION_INFO = ${json};
/* tslint:enable */
`, { flag: 'w', encoding : 'utf-8' });